config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  root "pages#home"
  get "pages/home", to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
  end

  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :ingredients, except: [:destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 5, maximum: 500 }

    belongs_to :chef
    validates :chef_id, presence: true
    default_scope -> { order(updated_at: :desc) }

    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients

    has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end

    def show
        @comment = Comment.new
        @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipes_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = "recipe created successfully!"
            redirect_to recipe_path(@recipe)
        else
            render 'new', status: 300
        end
    end

    def edit
    end

    def update
        if @recipe.update(recipes_params)
            flash[:success] = "recipe updated successfully!"
            redirect_to recipe_path(@recipe)
        else
            render 'edit', status: 300
        end
    end

    def destroy
        Recipe.find(params[:id]).destroy
        flash[:success] = "recipe deleted successfully!"
        redirect_to recipes_path
    end

    private

        def find_recipe
            @recipe = Recipe.find(params[:id])
        end

        def recipes_params
            params.require(:recipe).permit(:name, :description, ingredient_ids: [])
        end

        def require_same_user
            if current_chef != @recipe.chef and !current_chef.admin?
                flash[:danger] = "You can only edit destroy to your own recipes."
                redirect_to recipes_path
            end
        end

end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
 
<div class="rows">
    <div class="col-md-12">
        <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :name %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name, class: "form-control", placeholder: "Name of Recipe", autofocus: true %>
                </div>                
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :description %>
                </div>
                <div class="col-md-8">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create Recipe" %>
                </div>             
            </div>
            <div class="form-group">
                <div class="rows">
                    <div class="col-md-offset-2 col-md-8">
                        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
                            <% cb.label(class: "checkbox-inline input-checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
                        <% end %>
                    </div>
                </div>           
            </div>
            <br>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit class: "btn btn-xlarge btn-lg" %>
                </div>            
            </div>
        <% end %>
        <div class="col-md-offset-4 col-md-4 colormatch">
            [ <%= link_to "Cancel Request and Back to Recipes listing.", recipes_path %> ]
        </div>
    </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
    <div class="row" >
        <div class="col-md-2" >
            <section class="chef_info center" >
                <%= gravatar_for(recipe.chef, size: 120) %>
            </section>
        </div>
        <div class="col-md-8 well" >
            <h4><%= link_to recipe.name.capitalize, recipe_path(recipe) %></h4>
            <p>
                <%= truncate(recipe.description, length: 150) %>
            </p>
            <% if recipe.ingredients.any? %>
                <p>Ingredients: <%= render recipe.ingredients %> </p>
            <% end %>
            <p>
                <span class="quiet" >
                    <small>
                        Created by <%= link_to recipe.chef.chefname.capitalize, recipe.chef %> <%= time_ago_in_words(recipe.created_at) %> ago
                        | <%= pluralize(recipe.comments.count, 'Comment') %>
                    </small>
                </span>
            </p>
            <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
                <div class="recipe-actions">
                    <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
                    <%= link_to ('Delete this recipe'), recipe_path(recipe), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
                </div>
            <% end %>
        </div>
    </div>
    <hr/>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Listing all Recipes" %>

<div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero">
    <ul class=”pagination”>
        <li class="disabled"> 
            <%= will_paginate(@recipes, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font" ) %>
        </li>
    </ul>
</div>

<%= render 'recipe', obj: @recipes %>

<div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero">
    <ul class=”pagination”>
        <li class="disabled"> 
            <%= will_paginate(@recipes, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font" ) %>
        </li>
    </ul>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class = "rows">
    <div class="well col-md-8 col-md-offset-2" >
        <h4 class="center description" >
            <strong>
                Steps:
            </strong>
        </h4>
        <hr/>
        <%= simple_format(@recipe.description) %>
        <hr/>
        <% if @recipe.ingredients.any? %>
            <p>Ingredients: <%= render @recipe.ingredients %> </p>
        <% end %>
        <div class="pull-right" >
            <p class="center" >
                <em>
                    Created By:
                </em>
            </p>
            <p class="center" >
                <%= link_to gravatar_for(@recipe.chef), @recipe.chef %>
            </p>
            <p class="center" >
                <small>
                    <%= @recipe.chef.chefname.capitalize %>
                </small>
                <div class="pull-right" >
                    created: <%= time_ago_in_words(@recipe.created_at) %> ago
                </div>
            </p>
        </div>
        <div class="recipe-actions">
            <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?)%>
                <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
                <%= link_to ('Delete this recipe'), recipe_path(@recipe), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
            <% end %>    
            <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
        </div>
    </div>
</div>


<% if logged_in? %> 
    <div class="rows">
        <div class="col-md-8 col-md-offset-2">
            <h3>Comments:</h3>
            <hr/>
            <%= form_for([@recipe, @comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>
                <div class="form-group">
                    <div class="control-label col-md-2">
                        <%= f.label :description, "Comment" %>
                    </div>
                    <div class="col-md-8">
                        <%= f.text_area :description, rows: 7, class: "form-control", placeholder: "Enter comment here" %>
                    </div>             
                </div>
                <br>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <%= f.submit "Submit comment", class: "btn btn-xlarge btn-lg" %>
                    </div>            
                </div>
            <% end %>
            <hr/>
        </div>
    </div>
<% end %>


<% if @recipe.comments != 0 %>
    <div class="rows">
        <div class="col-md-8 col-md-offset-2" >
            <h3>Prior Comments:</h3>
            <div id="messages">
                <%= render partial: 'comments/comments', object: @comments %>
            </div>
        </div>
    </div>
<% else %>
    <div class="rows">
        <div class="col-md-8 col-md-offset-2" >
            <h3>No Comments yet!</h3>
        </div>
    </div>
<% end %>